{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "LegistCP",
    "description" : "LegistCP",
    "version" : "01"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/Kvakun/LegistCP/01",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : { },
  "components" : { }
}